FROM python:3.11-slim

WORKDIR /app
COPY ./source-data/data-generator.py .

RUN pip install faker psycopg2-binary python-dotenv

COPY .env .env

CMD ["sh", "-c", "sleep 10 && python data-generator.py"]
