FROM jupyter/base-notebook

USER root
RUN apt-get update && apt-get install -y openjdk-11-jdk && apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN pip install apache-flink==1.19.2